# RUN FIRST ON ROOT WITH NEXT LINE UNCOMMENTED TO CREATE A NEW USER
# THEN USE THAT NEW USER AND COMMENT THE LINES AGAIN.

# CREATE USER IF NOT EXISTS web@'localhost' IDENTIFIED BY 'web';
# GRANT ALL PRIVILEGES ON WEB.* TO 'web'@'localhost';
DROP DATABASE IF EXISTS `WEB`;
CREATE DATABASE `WEB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `WEB`;

CREATE TABLE `ADMIN`(
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY(username)
)Engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BLOCK`(
	ID INT AUTO_INCREMENT NOT NULL,
	population INT DEFAULT 0,
	capacity INT DEFAULT 0,
	distribution INT DEFAULT 2,
	PRIMARY KEY(ID)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `POINT`(
	ID INT AUTO_INCREMENT NOT NULL,
	BLOCK_ID INT NOT NULL,
	x DOUBLE(30,25),
	y DOUBLE(30,25),
	PRIMARY KEY(ID),
	CONSTRAINT POINT_BLOCK_ID
		FOREIGN KEY(BLOCK_ID) REFERENCES `BLOCK`(ID)
		ON UPDATE CASCADE ON DELETE CASCADE
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CENTROID`(
	ID INT AUTO_INCREMENT NOT NULL,
	BLOCK_ID INT NOT NULL,
	x DOUBLE(30,25),
	y DOUBLE(30,25),
	PRIMARY KEY(ID),
	CONSTRAINT CENTROID_BLOCK_ID
		FOREIGN KEY(BLOCK_ID) REFERENCES `BLOCK`(ID)
		ON UPDATE CASCADE ON DELETE CASCADE
)Engine=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ADMIN` VALUES
("dsa","123");
INSERT INTO `ADMIN` VALUES
("ασδ","123");